services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "7545:7545"
    command: ganache-cli -h 0.0.0.0 -p 7545 -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
    networks:
      - blockchain

  client:
    build: ./client
    volumes:
      - ./client:/app
    depends_on:
      - ganache
    networks:
      - blockchain
    stdin_open: true
    tty: true

networks:
  blockchain:
    driver: bridge

    

